### ISSUE TITLE
window.crypto.subtle is unavailable

### ISSUE THREAD

**Issue by alexkreidler** [AxaFrance/react-oidc#1028]
### Issue and Steps to Reproduce

I really love this library and have used it with Keycloak in the past. Unfortunately now I'm getting a weird error on Firefox and Chrome. I have a React app with Vite and React Router.

To reproduce: follow the [setup instructions from the README](https://github.com/AxaFrance/react-oidc#getting-started). Then make a component with a button that calls the `login` function. You'll see the error below.

### Versions
```
"@axa-fr/react-oidc": "^6.16.12",
"react": "^18.2.0",
"react-dom": "^18.2.0",
```
tested on Firefox 111.0.1 (64-bit) and Chrome Version 111.0.5563.147 (Official Build) (64-bit)

### Screenshots
![image](https://user-images.githubusercontent.com/11166947/230755324-2bde1a74-cf8c-4d79-9200-aac82366bb00.png)

#### Expected
Successfully redirects to Keycloak login page and logs in 
#### Actual
The user sees the default error component with text:
```
Error authentication
An error occurred during authentication.
```

The console has this message:
```
Uncaught (in promise) Error: window.crypto.subtle is unavailable.
    at deriveChallengeAsync (crypto.ts:53:29)
    at requests.ts:121:33
    at Generator.next (<anonymous>)
    at cache.ts:21:22
    at new Promise (<anonymous>)
    at __awaiter (cache.ts:21:22)
    at requests.ts:118:100
    at login.ts:65:59
    at Generator.next (<anonymous>)
    at fulfilled (route-utils.ts:79:1)
```

**Comment by alexkreidler** [comment]
BTW I tried reverting to `"@axa-fr/react-oidc": "^6.12.1",` and it worked perfectly

**Comment by guillaume-chervet** [comment]
hi @alexkreidler, thank you very much for your issue.

That very strange. Do you have a template of your create app + vite?
It come from here but, I need to reproduce it to understand: https://github.com/AxaFrance/react-oidc/blob/master/packages/react/src/oidc/vanilla/crypto.ts

**Comment by abhilashlr7** [comment]
We used to get this same error, this was resolved after running local on https instead of http.

**Comment by guillaume-chervet** [comment]
Thank you @abhilashlr7 for you feedback. I need to add this in a FAQ
