### ISSUE TITLE
OidcKeepAliveServiceWorker.json requests failing following pull request #967

### ISSUE THREAD

**Issue by dcopestake** [AxaFrance/react-oidc#1029]
### Issue and Steps to Reproduce

Following the merge of a previous pull request #967 from me to solve issue #862, unfortunately this introduced an error where the `OidcKeepAliveServiceWorker.json` requests were failing because of the `GET` fetch requests not being allowed to contain a body. This results in the SW throwing the exception `TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.`.

Should be showing for everyone I think so reproducing should be relatively straightforward! Apologies.

### Versions

v6.16.12

**Comment by wooandoo** [comment]
the problem is still present on version "@axa-fr/react-oidc": "6.16.14", but the error is now logged as:

```
OidcKeepAliveServiceWorker.json?minSleepSeconds=150 net::ERR_FAILED

TypeError: Failed to fetch
    at keepAlive (initWorker.ts:114:25)
```

**Comment by anonkey** [comment]
> the problem is still present on version "@axa-fr/react-oidc": "6.16.14", but the error is now logged as:
> 
> ```
> OidcKeepAliveServiceWorker.json?minSleepSeconds=150 net::ERR_FAILED
> 
> TypeError: Failed to fetch
>     at keepAlive (initWorker.ts:114:25)
> ```

Creating an OidcKeepAliveServiceWorker.json with "{}" into it fixed this problem for me

**Comment by hsul-git** [comment]
Same problem here:

`initWorker.ts:114     GET http://127.0.0.1:3000/OidcKeepAliveServiceWorker.json?minSleepSeconds=240 net::ERR_FAILED`
