### ISSUE TITLE
Cannot read properties of undefined (reading 'silent_login_uri')

### ISSUE THREAD

**Issue by hxuanhung** [AxaFrance/react-oidc#1044]
### Issue and Steps to Reproduce
I have the following configuration:

const baseConfiguration = {
  authority: `${process.env.REACT_APP_IAM_AUTHORITY}/realms/FPT`,
  client_id: `${process.env.REACT_APP_IAM_CLIENT_ID}`,
  scope: 'openid',
  // service_worker_relative_url: '/OidcServiceWorker.js',
  silent_login_uri: window.location.origin + '/auth/silent-callback',
  service_worker_only: true,
  redirect_uri: window.location.origin + '/auth/callback',
  silent_redirect_uri: window.location.origin + '/auth/silent-callback', // Optional activate silent-signin that use cookies between OIDC server and client javascript to restore the session
  // token_renew_mode: TokenRenewMode.access_token_invalid, // https://github.com/AxaFrance/react-oidc/issues/892#issuecomment-1292108369
};

TypeError: Cannot read properties of undefined (reading 'silent_login_uri')
    at new t (oidc.ts:84:44)
    at j (oidc.ts:53:26)
    at Function.value (oidc.ts:132:16)
    at Function.value (vanillaOidc.ts:28:37)
    at z (OidcProvider.tsx:96:28)
    at t.OidcProvider (OidcProvider.tsx:164:18)
    at aa (react-dom.production.min.js:157:137)
    at qs (react-dom.production.min.js:267:460)
    at Tl (react-dom.production.min.js:250:347)
    at El (react-dom.production.min.js:250:278)

### Versions
"@axa-fr/react-oidc": "^6.17.0"
### Screenshots
<img width="891" alt="image" src="https://user-images.githubusercontent.com/11139923/235680983-a5d4ab9d-0adc-4e04-baf9-03ad8a2f3f99.png">

#### Actual
TypeError: Cannot read properties of undefined (reading 'silent_login_uri')
    at new t (oidc.ts:84:44)
    at j (oidc.ts:53:26)
    at Function.value (oidc.ts:132:16)
    at Function.value (vanillaOidc.ts:28:37)
    at z (OidcProvider.tsx:96:28)
    at t.OidcProvider (OidcProvider.tsx:164:18)
    at aa (react-dom.production.min.js:157:137)
    at qs (react-dom.production.min.js:267:460)
    at Tl (react-dom.production.min.js:250:347)
    at El (react-dom.production.min.js:250:278)
### Additional Details

- Installed packages:

**Comment by guillaume-chervet** [comment]
Hi @hxuanhung , thank you for your issue.
I will try to take a look today.
From memory it is just a configuration issue.

**Comment by guillaume-chervet** [comment]
Hi @hxuanhung , do you have the problem if you clone and run the demo with your configuration?

**Comment by hxuanhung** [comment]
@guillaume-chervet I dont see that on localhost, it only happens in prod build. You can try to go to my app here https://dashboard-dev.chatbd.ai/auth/login while open the dev console and turn on Preserve log. I implement quite a hacky solution if the app return that error I would force reload the page.

**Comment by guillaume-chervet** [comment]
Hi @hxuanhung , sorry for thz delay. I will try to take a look tomorrow morning.

**Comment by hxuanhung** [comment]
Hi @guillaume-chervet, did you have a chance to look at that? 🙌

**Comment by guillaume-chervet** [comment]
hi @hxuanhung ,

Hi have tried to reproduce it whithout success.
I have looked from where the error come from.

I think your app is sending an null or undefined configuration to OidcProvider the first time. The error come from Oidc constructor.

![image](https://github.com/AxaFrance/react-oidc/assets/52236059/2940bb1e-e928-4257-8769-dd632ef5c208)
